# Generated by Django 4.2.17 on 2024-12-20 10:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredDirections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_lat', models.IntegerField()),
                ('from_lon', models.IntegerField()),
                ('to_lat', models.IntegerField()),
                ('to_lon', models.IntegerField()),
                ('directions_response', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
