# Generated by Django 5.1.4 on 2024-12-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_end_time_alter_job_max_workers_and_more'),
        ('jobs', '0002_storeddirections'),
    ]

    operations = [
    ]
