# Generated by Django 4.2.17 on 2024-12-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_merge_20241220_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimona',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('success', models.BooleanField(null=True)),
                ('reason', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobapplication')),
            ],
        ),
    ]
