# Generated by Django 4.2.20 on 2025-05-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_tag_job_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="special_committee",
            field=models.TextField(blank=True, null=True),
        ),
    ]
