# Generated by Django 4.2.22 on 2025-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_tag_special_committee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimona",
            name="id",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
