# Generated by Django 4.2.22 on 2025-06-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_dimona_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimona",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
