services:
  api:
    network_mode: "host"
    expose:
      - "80"
    build:
      context: ./src/
      dockerfile: ../docker/api/Dockerfile
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: on-failure

  celery_worker:
    build:
      context: ./src/
      dockerfile: ../docker/api/Dockerfile
    command: celery -A api worker -l info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: on-failure
