# Generated by Django 4.2.17 on 2024-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=256, null=True)),
                ('house_number', models.CharField(max_length=8, null=True)),
                ('box_number', models.CharField(max_length=8, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('zip_code', models.CharField(max_length=16, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('latitude', models.FloatField(max_length=16, null=True)),
                ('longitude', models.FloatField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
