# Generated by Django 4.2.17 on 2024-12-24 09:34

import apps.core.models.export_file
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('file_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=apps.core.models.export_file.ExportFile.get_upload_path)),
            ],
        ),
    ]
