# Generated by Django 5.1.4 on 2024-12-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='billing_address',
            new_name='customer_billing_address',
        ),
        migrations.RenameField(
            model_name='workerprofile',
            old_name='address',
            new_name='worker_address',
        ),
    ]
