# Generated by Django 4.2.17 on 2025-01-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="special_committee",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
