# Generated by Django 4.2.17 on 2024-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_favoriteaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_duration',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
