# Generated by Django 4.2.17 on 2025-01-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_workerprofile_worker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='worker_type',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('student', 'Student'), ('flexi', 'Flexi')], default='student', max_length=10),
        ),
    ]
