# Generated by Django 5.1.4 on 2024-12-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
    ]
