# Generated by Django 4.2.17 on 2025-01-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_jobtype_location_workerprofile_onboard_flow_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workerprofile",
            old_name="onboard_flow",
            new_name="has_passed_onboarding",
        ),
    ]
