# Generated by Django 4.2.17 on 2024-12-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0018_remove_group_app_secret'),
        ('authentication', '0005_remove_customerprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extension', serialize=False, to='auth.group')),
                ('group_secret', models.CharField(max_length=180, null=True)),
            ],
        ),
    ]
