# Generated by Django 4.2.17 on 2025-01-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_onboard_flow_workerprofile_has_passed_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboardflow',
            name='car_washing_experience_type',
        ),
        migrations.RemoveField(
            model_name='dashboardflow',
            name='chauffeur_experience_type',
        ),
        migrations.RemoveField(
            model_name='dashboardflow',
            name='cleaning_experience_type',
        ),
        migrations.RemoveField(
            model_name='dashboardflow',
            name='gardening_experience_type',
        ),
        migrations.RemoveField(
            model_name='dashboardflow',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='dashboardflow',
            name='situation_type',
        ),
        migrations.RemoveField(
            model_name='dashboardflow',
            name='waiter_experience_type',
        ),
        migrations.RemoveField(
            model_name='dashboardflow',
            name='work_type',
        ),
        migrations.AddField(
            model_name='jobtype',
            name='icon',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='UserJobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('skilled', 'Skilled'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.jobtype')),
            ],
        ),
        migrations.AddField(
            model_name='dashboardflow',
            name='job_types',
            field=models.ManyToManyField(related_name='dashboard_flow_job_type', to='authentication.userjobtype'),
        ),
        migrations.AddField(
            model_name='dashboardflow',
            name='situation_types',
            field=models.ManyToManyField(related_name='dashboard_flow_situation_type', to='authentication.situationtype'),
        ),
        migrations.AddField(
            model_name='dashboardflow',
            name='work_types',
            field=models.ManyToManyField(related_name='dashboard_flow_work_type', to='authentication.worktype'),
        ),
    ]
