# Generated by Django 4.2.17 on 2025-01-30 12:20

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0010_jobtype_weight_location_weight_worktype_weight_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="situationtype",
            name="weight",
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
