# Generated by Django 4.2.20 on 2025-04-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_tag_job_tag"),
        ("authentication", "0011_situationtype_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.tag",
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="tags",
            field=models.ManyToManyField(blank=True, to="jobs.tag"),
        ),
    ]
