# Generated by Django 4.2.20 on 2025-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_situationtype_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='situationtype',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
