# Generated by Django 4.2.20 on 2025-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customerprofile_tag_workerprofile_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtype",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="situationtype",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
