# Generated by Django 4.2.18 on 2025-02-03 13:39

import apps.exports.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("file_name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=256, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.exports.models.ExportFile.get_upload_path
                    ),
                ),
            ],
        ),
    ]
